<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"常用语句类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChangyongyuju"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"成语学习类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChengyuxuexi"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"帖子类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryForum"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"基础类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJichu"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"情景学习类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryQingjingxuexi"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"诗词学习类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShicixuexi"
                    }

                ],
                "menu":"基础数据管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }

            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"常用语句管理",
                        "menuJump":"列表",
                        "tableName":"changyongyuju"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"常用语句留言管理",
                        "menuJump":"列表",
                        "tableName":"changyongyujuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"常用语句收藏管理",
                        "menuJump":"列表",
                        "tableName":"changyongyujuCollection"
                    }
                ],
                "menu":"常用语句管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"成语学习管理",
                        "menuJump":"列表",
                        "tableName":"chengyuxuexi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"成语学习留言管理",
                        "menuJump":"列表",
                        "tableName":"chengyuxuexiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"成语学习收藏管理",
                        "menuJump":"列表",
                        "tableName":"chengyuxuexiCollection"
                    }
                ],
                "menu":"成语学习管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"论坛管理",
                        "menuJump":"列表",
                        "tableName":"forum"
                    }
                ],
                "menu":"论坛管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"基础管理",
                        "menuJump":"列表",
                        "tableName":"jichu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"基础留言管理",
                        "menuJump":"列表",
                        "tableName":"jichuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"基础收藏管理",
                        "menuJump":"列表",
                        "tableName":"jichuCollection"
                    }
                ],
                "menu":"基础管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"情景学习管理",
                        "menuJump":"列表",
                        "tableName":"qingjingxuexi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"情景学习留言管理",
                        "menuJump":"列表",
                        "tableName":"qingjingxuexiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"情景学习收藏管理",
                        "menuJump":"列表",
                        "tableName":"qingjingxuexiCollection"
                    }
                ],
                "menu":"情景学习管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"诗词学习管理",
                        "menuJump":"列表",
                        "tableName":"shicixuexi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"诗词学习留言管理",
                        "menuJump":"列表",
                        "tableName":"shicixuexiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"诗词学习收藏管理",
                        "menuJump":"列表",
                        "tableName":"shicixuexiCollection"
                    }
                ],
                "menu":"诗词学习管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
,
{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"常用语句管理",
                        "menuJump":"列表",
                        "tableName":"changyongyuju"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"常用语句留言管理",
                        "menuJump":"列表",
                        "tableName":"changyongyujuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"常用语句收藏管理",
                        "menuJump":"列表",
                        "tableName":"changyongyujuCollection"
                    }
                ],
                "menu":"常用语句管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"成语学习管理",
                        "menuJump":"列表",
                        "tableName":"chengyuxuexi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"成语学习留言管理",
                        "menuJump":"列表",
                        "tableName":"chengyuxuexiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"成语学习收藏管理",
                        "menuJump":"列表",
                        "tableName":"chengyuxuexiCollection"
                    }
                ],
                "menu":"成语学习管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"论坛管理",
                        "menuJump":"列表",
                        "tableName":"forum"
                    }
                ],
                "menu":"论坛管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"基础管理",
                        "menuJump":"列表",
                        "tableName":"jichu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"基础留言管理",
                        "menuJump":"列表",
                        "tableName":"jichuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"基础收藏管理",
                        "menuJump":"列表",
                        "tableName":"jichuCollection"
                    }
                ],
                "menu":"基础管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"情景学习管理",
                        "menuJump":"列表",
                        "tableName":"qingjingxuexi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"情景学习留言管理",
                        "menuJump":"列表",
                        "tableName":"qingjingxuexiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"情景学习收藏管理",
                        "menuJump":"列表",
                        "tableName":"qingjingxuexiCollection"
                    }
                ],
                "menu":"情景学习管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"诗词学习管理",
                        "menuJump":"列表",
                        "tableName":"shicixuexi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"诗词学习留言管理",
                        "menuJump":"列表",
                        "tableName":"shicixuexiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"诗词学习收藏管理",
                        "menuJump":"列表",
                        "tableName":"shicixuexiCollection"
                    }
                ],
                "menu":"诗词学习管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
